Поиск классов и модулей в `src`.
EvilBeaver/oscript-library pull request #171
Opened 2017-06-24 19:48 UTC by dmpas

Расширено соглашение о стандартных каталогах. Теперь поиск модулей и
классов ведётся не только в корне библиотеки, но и в подкаталоге src.
Также разрешены английские синонимы для каталогов.

/cc @nixel2007 @artbear

2017-06-24 19:48 UTC, review-ninja commented
<a href="https://app.review.ninja/EvilBeaver/oscript-library/pull/171" target="_blank"><img src="https://app.review.ninja/32417757/pull/171/badge" alt="ReviewNinja"/>

2017-06-25 14:08 UTC, nixel2007 approved these changes

2017-06-25 18:48 UTC, EvilBeaver reviewed
Хитрец! А чо так можно было?

2017-06-26 08:54 UTC, artbear commented
@dmpas Перенеси, плиз, метод ОбработатьСтруктуруКаталоговПоСоглашению повыше, до используемых им методов, чтобы читать код как книгу

2017-06-26 08:55 UTC, artbear requested changes
Отличная правка, есть только одно мелкое замечание по структуре кода

2017-06-26 09:22 UTC, artbear approved these changes

2017-06-26 09:23 UTC, artbear commented
@EvilBeaver у тебя еще есть вопросы?
Мержим?

2017-07-17 17:53 UTC, dmpas commented
@EvilBeaver есть вопросы по этой доработке?

2017-07-17 18:02 UTC, merged